services:
  - type: web
    name: dothraki-eda
    runtime: python
    pythonVersion: "3.9.5"
    buildCommand: "./build.sh"
    startCommand: "gunicorn --config gunicorn_config.py app:app"
    envVars:
    
      - key: MONGO_URI
        value: "mongodb+srv://vgugan16:gugan2004@cluster0.qyh1fuo.mongodb.net/dL?retryWrites=true&w=majority"
      - key: DEPLOYMENT_ENV
        value: "production"